message(STATUS "CMake Module XXD Target Compiler Loaded")

include("${CMAKE_CURRENT_LIST_DIR}/check_program.cmake")

check_program("bash"    "BASH")
check_program("xxd"     "XXD")
check_program("uniq"    "UNIQ")
check_program("mv"      "MV")
check_program("mkdir"   "MKDIR")
check_program("date"    "DATE")
check_program("grep"    "GREP")
check_program("awk"     "AWK")
check_program("sed"     "SED")

# Remove old resource_file_list.h
message(STATUS "Removing old resource_file_list.h ...")
file(REMOVE "${CMAKE_BINARY_DIR}/include/res/resource_file_list.h")

# Generate resource_file_list.h
add_custom_command(
        OUTPUT "${CMAKE_BINARY_DIR}/include/res/resource_file_list.h"
        COMMAND ${BASH_EXECUTABLE} -c "echo '// Created on' $(${DATE_EXECUTABLE}) > \"${CMAKE_BINARY_DIR}/include/res/resource_file_list.h\""
        COMMAND ${BASH_EXECUTABLE} -c "echo '// This file is automatically generated by the build system.' >> \"${CMAKE_BINARY_DIR}/include/res/resource_file_list.h\""
        COMMAND ${BASH_EXECUTABLE} -c "echo '// !! DO NOT DIRECTLY MODIFY THIS FILE !! INSTEAD, MODIFY THE BUILD SCRIPT !!' >> \"${CMAKE_BINARY_DIR}/include/res/resource_file_list.h\""
        COMMAND ${BASH_EXECUTABLE} -c "echo '' >> \"${CMAKE_BINARY_DIR}/include/res/resource_file_list.h\""
        COMMAND ${BASH_EXECUTABLE} -c "echo '#ifndef SYSDARFT_RESOURCE_FILE_LIST_H' >> \"${CMAKE_BINARY_DIR}/include/res/resource_file_list.h\""
        COMMAND ${BASH_EXECUTABLE} -c "echo '#define SYSDARFT_RESOURCE_FILE_LIST_H' >> \"${CMAKE_BINARY_DIR}/include/res/resource_file_list.h\""

        COMMAND ${BASH_EXECUTABLE} -c "echo '' >> \"${CMAKE_BINARY_DIR}/include/res/resource_file_list.h\""
        COMMAND ${BASH_EXECUTABLE} -c "echo 'const char * file_list[] = {' >> \"${CMAKE_BINARY_DIR}/include/res/resource_file_list.h\""
        COMMAND ${BASH_EXECUTABLE} -c "echo '};' >> \"${CMAKE_BINARY_DIR}/include/res/resource_file_list.h\""
        COMMAND ${BASH_EXECUTABLE} -c "echo '' >> \"${CMAKE_BINARY_DIR}/include/res/resource_file_list.h\""

        COMMAND ${BASH_EXECUTABLE} -c "echo '' >> \"${CMAKE_BINARY_DIR}/include/res/resource_file_list.h\""
        COMMAND ${BASH_EXECUTABLE} -c "echo 'const unsigned char * file_content_vector[] = {' >> \"${CMAKE_BINARY_DIR}/include/res/resource_file_list.h\""
        COMMAND ${BASH_EXECUTABLE} -c "echo '};' >> \"${CMAKE_BINARY_DIR}/include/res/resource_file_list.h\""
        COMMAND ${BASH_EXECUTABLE} -c "echo '' >> \"${CMAKE_BINARY_DIR}/include/res/resource_file_list.h\""

        COMMAND ${BASH_EXECUTABLE} -c "echo '' >> \"${CMAKE_BINARY_DIR}/include/res/resource_file_list.h\""
        COMMAND ${BASH_EXECUTABLE} -c "echo 'const unsigned int file_content_len_vector[] = {' >> \"${CMAKE_BINARY_DIR}/include/res/resource_file_list.h\""
        COMMAND ${BASH_EXECUTABLE} -c "echo '};' >> \"${CMAKE_BINARY_DIR}/include/res/resource_file_list.h\""
        COMMAND ${BASH_EXECUTABLE} -c "echo '' >> \"${CMAKE_BINARY_DIR}/include/res/resource_file_list.h\""

        COMMAND ${BASH_EXECUTABLE} -c "echo '#endif // SYSDARFT_RESOURCE_FILE_LIST_H' >> \"${CMAKE_BINARY_DIR}/include/res/resource_file_list.h\""
        WORKING_DIRECTORY ${CMAKE_BINARY_DIR}
        COMMENT "Generating final resource_file_list.h"
        VERBATIM
)

# Initialize target for resource file list
add_custom_target(ResourceFileListInit ALL
        DEPENDS "${CMAKE_BINARY_DIR}/include/res/resource_file_list.h"
)

# Remove duplicated entries from resource file list
add_custom_target(ExcludeFileListDuplicatedEntries ALL
        COMMAND ${UNIQ_EXECUTABLE} "${CMAKE_BINARY_DIR}/include/res/resource_file_list.h" > "${CMAKE_BINARY_DIR}/include/res/resource_file_list.h.bak"
        COMMAND ${MV_EXECUTABLE} "${CMAKE_BINARY_DIR}/include/res/resource_file_list.h.bak" "${CMAKE_BINARY_DIR}/include/res/resource_file_list.h"
        VERBATIM
)

# Function to add a target for xxd conversion and update resource file list
function(sysdarft_add_xxd_target TARGET_NAME TARGET_FILE)
    add_custom_command(
            OUTPUT "${CMAKE_BINARY_DIR}/res/${TARGET_NAME}.cpp"
            # Compile file:
            COMMAND ${XXD_EXECUTABLE} -i "${CMAKE_SOURCE_DIR}/${TARGET_FILE}" > "${CMAKE_BINARY_DIR}/res/${TARGET_NAME}.cpp"

            # Add file path to file_list
            COMMAND ${BASH_EXECUTABLE} -c "sed -i '/const char \\* file_list\\[\\] = {/a\\\t\"${TARGET_FILE}\",' \"${CMAKE_BINARY_DIR}/include/res/resource_file_list.h\""

            # Generate extern definitions under #define SYSDARFT_RESOURCE_FILE_LIST_H
            COMMAND ${BASH_EXECUTABLE} -c "cat \"${CMAKE_BINARY_DIR}/res/${TARGET_NAME}.cpp\" | grep \"unsigned char\" | awk -F' = ' '{print $1}' | sed 's/\\[\\]//g' | sed 's/^/extern /; s/\$\/; \\/\* file content \*\\//' | sed -i '/\\#define SYSDARFT_RESOURCE_FILE_LIST_H/r /dev/stdin' \"${CMAKE_BINARY_DIR}/include/res/resource_file_list.h\""
            COMMAND ${BASH_EXECUTABLE} -c "cat \"${CMAKE_BINARY_DIR}/res/${TARGET_NAME}.cpp\" | grep \"unsigned int\" | awk -F' = ' '{print $1}' | sed 's/^/extern /; s/\$\/; \\/\* file content length \*\\//' | sed -i '/\\#define SYSDARFT_RESOURCE_FILE_LIST_H/r /dev/stdin' \"${CMAKE_BINARY_DIR}/include/res/resource_file_list.h\""
            COMMAND ${BASH_EXECUTABLE} -c "echo | sed -i '/\\#define SYSDARFT_RESOURCE_FILE_LIST_H/r /dev/stdin' \"${CMAKE_BINARY_DIR}/include/res/resource_file_list.h\""

            # Add definition to vectors
            COMMAND ${BASH_EXECUTABLE} -c "VARIABLE=$(cat \"${CMAKE_BINARY_DIR}/res/${TARGET_NAME}.cpp\" | grep \"unsigned char\" | awk -F' = ' '{print $1}' | awk '{print $3}' | sed 's/\\[\\]//g'); echo -e \"\\t\"$VARIABLE\"_vec = $VARIABLE,\" | sed -i '/const unsigned char \\* file_content_vector\\[\\] = {/r /dev/stdin' \"${CMAKE_BINARY_DIR}/include/res/resource_file_list.h\""
            COMMAND ${BASH_EXECUTABLE} -c "VARIABLE=$(cat \"${CMAKE_BINARY_DIR}/res/${TARGET_NAME}.cpp\" | grep \"unsigned int\" | awk -F' = ' '{print $1}' | awk '{print $3}'); echo -e \"\\t\"$VARIABLE\"_vec = $VARIABLE,\" | sed -i '/const unsigned int file_content_len_vector\\[\\] = {/r /dev/stdin' \"${CMAKE_BINARY_DIR}/include/res/resource_file_list.h\""

            MAIN_DEPENDENCY "${CMAKE_SOURCE_DIR}/${TARGET_FILE}" "${CMAKE_BINARY_DIR}/include/res/resource_file_list.h"
            DEPENDS "${CMAKE_SOURCE_DIR}/${TARGET_FILE}"
            WORKING_DIRECTORY "${CMAKE_BINARY_DIR}"
            COMMENT "Generating resource header file..."
            VERBATIM
    )

    add_custom_target(${TARGET_NAME} ALL
            DEPENDS "${CMAKE_BINARY_DIR}/res/${TARGET_NAME}.cpp"
    )

    add_dependencies(ExcludeFileListDuplicatedEntries ${TARGET_NAME})
endfunction()

message(STATUS "Setting up resource include directory at `${CMAKE_BINARY_DIR}/include`")
execute_process(
        COMMAND ${MKDIR_EXECUTABLE} -p "${CMAKE_BINARY_DIR}/include"
)
include_directories("${CMAKE_BINARY_DIR}/include")
