name: CMake on Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Update APT
      run: sudo apt update -y && sudo apt-mark hold firefox && sudo apt upgrade -y

    - name: Install dependencies
      run: sudo apt install python3 python3-pip python3-venv cmake build-essential xvfb libfuse-dev fuse3 vim

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DRESOURCE_PACK_TMP_DIR="$PWD/_tmp"

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: bash -c "source ${{github.workspace}}/build/PythonVirtualEnvironment/bin/activate; xvfb-run ctest; deactivate"
